#!/usr/bin/env bash
# Init script that manages manage_my_process daemon

PIDFILE="/var/run/my_process.pid"
SCRIPT="./manage_my_process"

start() {
    $SCRIPT &
    echo $! > $PIDFILE
    echo "manage_my_process started"
}

stop() {
    if [ -f $PIDFILE ]; then
        kill "$(cat $PIDFILE)"
        rm -f $PIDFILE
        echo "manage_my_process stopped"
    fi
}

restart() {
    if [ -f $PIDFILE ]; then
        kill "$(cat $PIDFILE)"
        rm -f $PIDFILE
    fi
    $SCRIPT &
    echo $! > $PIDFILE
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
